Listeners:
  TinyListeners:
    Display-Unriding: false
Locale:
  Console: en_us
  Default-To:
    es_es:
      - es_ar
      - es_cl
      - es_ec
      - es_mx
      - es_uy
      - es_ve
    pt_pt:
      - pt_br
    fr_fr:
      - fr_ca
WeaponMechanics:
  Actionbar-Weapon-Info-Display: false