name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_package:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.head_commit.message, '-package') }}
    steps:
      - uses: actions/checkout@v1
      - name: â˜•ï¸Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: ğŸ“¦Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --file ci-pom.xml deploy
